In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
arr = np.array(l) # converted to array

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr1 = np.array([[1,2],[3,4]])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr2 = np.asarray([1,2,3,4,5]) # also .asanyarray()

In [9]:
type(arr2)

numpy.ndarray

In [10]:
b = np.matrix(l) # by default 2D

In [11]:
b

matrix([[1, 2, 3, 4, 5]])

In [12]:
np.asarray(b) # array me convert nhi karga, because matrix is subset of array

array([[1, 2, 3, 4, 5]])

In [13]:
c = arr # c take refernce of arr[shallow copy]

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
c

array([1, 2, 3, 4, 5])

In [16]:
c[0] = 100

In [17]:
c

array([100,   2,   3,   4,   5])

In [18]:
arr

array([100,   2,   3,   4,   5])

In [19]:
d = np.copy(arr) # deep copy

In [20]:
d[2]= 400

In [21]:
d

array([100,   2, 400,   4,   5])

In [22]:
arr

array([100,   2,   3,   4,   5])

In [23]:
np.fromfunction(lambda i,j :i==j,(3,3)) # generate function according to given function in 3x3

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
np.fromfunction(lambda i,j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [27]:
iterable = (i*i for i in range(5))
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [29]:
np.fromstring('123 567 897',sep=' ')

array([123., 567., 897.])

In [30]:
# data type in numpy

In [31]:
arr

array([100,   2,   3,   4,   5])

In [32]:
arr.ndim

1

In [33]:
arr1

array([[1, 2],
       [3, 4]])

In [35]:
arr1.ndim

2

In [36]:
arr.size # number ele in array

5

In [37]:
arr1.size

4

In [38]:
arr.shape

(5,)

In [39]:
arr1.shape # 2 -> row and 2 column

(2, 2)

In [40]:
arr3 = np.array([(1.4,45,32),(23,46,78)])

In [41]:
arr3.dtype

dtype('float64')

In [42]:
# producing floating point number

In [43]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [44]:
np.arange(2.3,5.8,0.4)

array([2.3, 2.7, 3.1, 3.5, 3.9, 4.3, 4.7, 5.1, 5.5])

In [46]:
np.linspace(1,5,10)  # line 1 to 5 ko 10 parts me break krdeta hai

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [50]:
np.linspace(1,5,10).ndim

1

In [47]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
arr5 = np.zeros((3,4,2))

In [52]:
arr5.ndim

3

In [53]:
arr5 + 6

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [55]:
np.empty((3,5))

array([[1.4115e-320, 7.7771e-320, 5.3359e-321, 9.5572e-320, 2.8547e-320],
       [2.8547e-320, 9.5572e-320, 5.3359e-321, 7.7771e-320, 1.4115e-320],
       [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000]])

In [56]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.logspace(2,5,10) # log nikalta hai

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [60]:
np.logspace(2,5,10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [61]:
# usefull function

In [76]:
# ramdom function
ran = np.random.randn(3,4) # 3 row and 4 column,
# produce data based on standart normal distribution mean =0, st = st

In [77]:
import pandas as pd

In [78]:
pd.DataFrame(ran)

          0         1         2         3
0 -0.308688 -0.190399 -0.389652  0.792929
1  1.617003 -0.722243 -0.891546  0.775159
2 -1.248972 -0.412424  0.580550  1.816962

In [79]:
ran1 = np.random.rand(3,4) # rnadom data not based on normal distribution

In [80]:
pd.DataFrame(ran1)

          0         1         2         3
0  0.439162  0.331795  0.263482  0.020167
1  0.765790  0.439833  0.388148  0.657108
2  0.348492  0.358216  0.968314  0.852760

In [85]:
dt = np.random.randint(1,100,(3,4))

In [127]:
dt

array([[15, 48, 68, 10],
       [27, 12, 48, 29],
       [99, 38, 79, 49]], dtype=int32)

In [88]:
pd.DataFrame(dt).to_csv('random_data')

In [89]:
arr6 = np.random.rand(3,4)

In [90]:
arr6

array([[0.07203103, 0.86513509, 0.77435562, 0.78697268],
       [0.13911218, 0.50602067, 0.13939601, 0.96678867],
       [0.63699992, 0.57227039, 0.20651654, 0.40513288]])

In [92]:
arr6.reshape(6,-1) # reduce 1 dimension

array([[0.07203103, 0.86513509],
       [0.77435562, 0.78697268],
       [0.13911218, 0.50602067],
       [0.13939601, 0.96678867],
       [0.63699992, 0.57227039],
       [0.20651654, 0.40513288]])

In [94]:
arr7 = arr6.reshape(6,-1432345456)

In [95]:
arr7[1]

array([0.77435562, 0.78697268])

In [97]:
arr7[1][1]

np.float64(0.7869726783987067)

In [98]:
arr7[2:5,1]

array([0.50602067, 0.96678867, 0.57227039])

In [100]:
arr8 = np.random.randint(1,100,(5,6))

In [101]:
arr8

array([[86, 23, 39, 57, 78, 14],
       [97, 64, 28, 29,  1, 41],
       [76, 76, 58, 90, 68, 26],
       [44, 41, 77, 54, 40, 32],
       [73, 79, 20, 29, 89, 13]], dtype=int32)

In [102]:
arr8>50

array([[ True, False, False,  True,  True, False],
       [ True,  True, False, False, False, False],
       [ True,  True,  True,  True,  True, False],
       [False, False,  True,  True, False, False],
       [ True,  True, False, False,  True, False]])

In [104]:
arr8[arr8>50]

array([86, 57, 78, 97, 64, 76, 76, 58, 90, 68, 77, 54, 73, 79, 89],
      dtype=int32)

In [106]:
arr9 = arr8

In [107]:
arr8 + arr9

array([[172,  46,  78, 114, 156,  28],
       [194, 128,  56,  58,   2,  82],
       [152, 152, 116, 180, 136,  52],
       [ 88,  82, 154, 108,  80,  64],
       [146, 158,  40,  58, 178,  26]], dtype=int32)

In [109]:
arr8 * arr9 # normal multiplication(index wise), not matrix multiplication

array([[7396,  529, 1521, 3249, 6084,  196],
       [9409, 4096,  784,  841,    1, 1681],
       [5776, 5776, 3364, 8100, 4624,  676],
       [1936, 1681, 5929, 2916, 1600, 1024],
       [5329, 6241,  400,  841, 7921,  169]], dtype=int32)

In [124]:
arr10= np.random.randint(1,100,(4,6))

In [125]:
arr11 = np.random.randint(1,100,(6,3))

In [126]:
# matrix multiplication
arr10@arr11

array([[17736, 16450, 14614],
       [16959, 13866,  8992],
       [18336, 23175, 18761],
       [16160, 20824, 13520]], dtype=int32)

In [129]:
arr/0

C:\Users\mohdy\AppData\Local\Temp\ipykernel_18792\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0

array([inf, inf, inf, inf, inf])

In [130]:
# numpy: Broadcasting

In [131]:
arr12 = np.zeros((4,4))

In [132]:
row = np.array([1,2,4,6])

In [133]:
arr12 + row # row wise broadcasting

array([[1., 2., 4., 6.],
       [1., 2., 4., 6.],
       [1., 2., 4., 6.],
       [1., 2., 4., 6.]])

In [135]:
row.T # tranpose, nhi rotate hoga minimim two coulmn requied to rotate

array([1, 2, 4, 6])

In [137]:
col= np.array([[4,5,3,7]])

In [138]:
arr12 + col

array([[4., 5., 3., 7.],
       [4., 5., 3., 7.],
       [4., 5., 3., 7.],
       [4., 5., 3., 7.]])

In [139]:
np.exp(arr12)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [140]:
np.log10(arr12)

C:\Users\mohdy\AppData\Local\Temp\ipykernel_18792\155814875.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr12)

array([[-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])