In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [3]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
# I want to drop any column
# df.drop('PassengerId') # error show that not found in axis
# df.drop('PassengerId',axis=1) # but not remove from original

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.drop('PassengerId',axis=1,inplace=True) # inplace True means permanently persist

In [7]:
# to remove row

In [8]:
df.drop(3,inplace=True)

In [9]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [10]:
# want that name became index
# df.set_index("Name") # but not persist

In [11]:
df.set_index("Name",inplace=True) # now permanent

In [12]:
# df.reset_index() # default index set karga

In [13]:
# dictionary to data frame
dic = {
    'key1':[1,2,3,4,65],
    'key2':[5,6,7,8,54],
    'key3':[12,3,2,14,4]
}

In [14]:
pd.DataFrame(dic)

   key1  key2  key3
0     1     5    12
1     2     6     3
2     3     7     2
3     4     8    14
4    65    54     4

In [15]:
# JSON to Data frame(do it)

In [16]:
df2 = pd.read_csv('file_example_save.csv')

In [17]:
df2 # have some NAN vale

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [18]:
df2.dropna() # remove all records have NAN but not permanent
# df2.dropna(inplace=True) # permanent

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [19]:
df2.dropna(axis=1) # remove all colums have NAN but not permanat

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500

In [20]:
df2.fillna("Ghazi") # NAN => ghazi

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Ghazi,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Ghazi,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Ghazi,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,Ghazi,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,Ghazi,1,2,W./C. 6607,23.4500,Ghazi,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Ghazi,Q

In [21]:
df.reset_index(inplace=True)

In [22]:
# I want to group the data

In [23]:
g = df.groupby('Survived')

In [24]:
g.sum()

,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Survived,,,,,,,,,,
0,"Braund, Mr. Owen HarrisAllen, Mr. William Henr...",1390,malemalemalemalemalemalemalefemalemalefemalema...,12985.50,304,181,A/5 2117137345033087717463349909A/5. 215134708...,12142.7199,E46C23 C25 C27B30C83F G73E31A5D26C110B58 B60D2...,SSQSSSSSQSSSCSSCSCSSSSSCSQCSSSCCSCSSCSSSSSCSSS...
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",666,femalefemalefemalefemalefemalefemalefemalemale...,8184.67,161,159,PC 17599STON/O2. 3101282347742237736PP 9549113...,16498.1294,C85G6C103D56A6B78D33C52B28F33C23 C25 C27D10 D1...,CSSCSSSSCSQSSQCQCCCQQCSSSSCSSSSSSQSSSCSSSQSCSC...

In [25]:
# g.mean() # not working

In [26]:
g1 = df.groupby('Pclass')

In [27]:
g1

In [28]:
g1.sum()

,Name,Survived,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",135,femalemalefemalemalemalemalefemalemalemalefema...,7076.42,89,77,PC 175991746311378311378819950PC 17601PC 17569...,18124.3125,C85E46C103A6C23 C25 C27B78D33B30C52B28C83C23 C...,CSSSSCCCSCCSSCSSSCCSSCSSSCSCSSSCCSSCCCCCSSQSSC...
2,"Nasser, Mrs. Nicholas (Adele Achem)Hewlett, Mr...",87,femalefemalemalemalemalemalefemalefemalefemale...,5168.83,74,70,237736248706244373239865248698C.A. 2457911668S...,3801.8417,D56F33E101F2F4F2DE101DF2F33DF33F4E101E77,CSSSSSSCSSSSSSSSSSSSCSSSCSSSSSSSCSSSSSSSSSSSSS...
3,"Braund, Mr. Owen HarrisHeikkinen, Miss. LainaA...",119,malefemalemalemalemalefemalefemalemalemalefema...,8924.92,302,193,A/5 21171STON/O2. 3101282373450330877349909347...,6714.6951,G6F G73F E69G6G6G6E10F G63F G73E121F38E121,SSSQSSSSSSQSCQSSCQSQCSSCSCQSQQCSSSCSCSCSSSSCSS...

In [29]:
df4 = df[['Name','Survived','Fare']][0:6]

In [30]:
df5 = df[['Name','Survived','Fare']][7:12]

In [31]:
df4

                                                Name  Survived     Fare
0                            Braund, Mr. Owen Harris         0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1  71.2833
2                             Heikkinen, Miss. Laina         1   7.9250
3                           Allen, Mr. William Henry         0   8.0500
4                                   Moran, Mr. James         0   8.4583
5                            McCarthy, Mr. Timothy J         0  51.8625

In [32]:
df5

                                                 Name  Survived     Fare
7   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1  11.1333
8                 Nasser, Mrs. Nicholas (Adele Achem)         1  30.0708
9                     Sandstrom, Miss. Marguerite Rut         1  16.7000
10                           Bonnell, Miss. Elizabeth         1  26.5500
11                     Saundercock, Mr. William Henry         0   8.0500

In [34]:
pd.concat([df4,df5]) # vertical merging

                                                 Name  Survived     Fare
0                             Braund, Mr. Owen Harris         0   7.2500
1   Cumings, Mrs. John Bradley (Florence Briggs Th...         1  71.2833
2                              Heikkinen, Miss. Laina         1   7.9250
3                            Allen, Mr. William Henry         0   8.0500
4                                    Moran, Mr. James         0   8.4583
5                             McCarthy, Mr. Timothy J         0  51.8625
7   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1  11.1333
8                 Nasser, Mrs. Nicholas (Adele Achem)         1  30.0708
9                     Sandstrom, Miss. Marguerite Rut         1  16.7000
10                           Bonnell, Miss. Elizabeth         1  26.5500
11                     Saundercock, Mr. William Henry         0   8.0500

In [36]:
pd.concat([df4,df5],axis=1) # horizontal merging

,Name,Survived,Fare,Name,Survived,Fare
0,"Braund, Mr. Owen Harris",0.0,7.2500,NaN,NaN,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1.0,71.2833,NaN,NaN,NaN
2,"Heikkinen, Miss. Laina",1.0,7.9250,NaN,NaN,NaN
3,"Allen, Mr. William Henry",0.0,8.0500,NaN,NaN,NaN
4,"Moran, Mr. James",0.0,8.4583,NaN,NaN,NaN
5,"McCarthy, Mr. Timothy J",0.0,51.8625,NaN,NaN,NaN
7,NaN,NaN,NaN,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1.0,11.1333
8,NaN,NaN,NaN,"Nasser, Mrs. Nicholas (Adele Achem)",1.0,30.0708
9,NaN,NaN,NaN,"Sandstrom, Miss. Marguerite Rut",1.0,16.7000
10,NaN,NaN,NaN,"Bonnell, Miss. Elizabeth",1.0,26.5500
11,NaN,NaN,NaN,"Saundercock, Mr. William Henry",0.0,8.0500

In [49]:
data1 = pd.DataFrame({'key1':[1,2,4,6,8,3],
                      'key2':[3,2,46,8,6,76],
                      'key3':[2,8,54,222,56,9]
                      })

In [56]:
data2 = pd.DataFrame({'key1': [1, 2, 44, 6, 8, 3],
                      'key2': [3, 2, 46, 87, 67,76],
                      'key3': [2, 81, 54, 22, 56, 9],
                      'key4':[76,43,78,98,60,66]
                      })

In [57]:
data1

   key1  key2  key3
0     1     3     2
1     2     2     8
2     4    46    54
3     6     8   222
4     8     6    56
5     3    76     9

In [58]:
data2

   key1  key2  key3  key4
0     1     3     2    76
1     2     2    81    43
2    44    46    54    78
3     6    87    22    98
4     8    67    56    60
5     3    76     9    66

In [59]:
# merge operation

In [60]:
pd.merge(data1,data2) # inner join karta hai

   key1  key2  key3  key4
0     1     3     2    76
1     3    76     9    66

In [61]:
pd.merge(data1,data2,how='left') # left join

   key1  key2  key3  key4
0     1     3     2  76.0
1     2     2     8   NaN
2     4    46    54   NaN
3     6     8   222   NaN
4     8     6    56   NaN
5     3    76     9  66.0

In [63]:
pd.merge(data1,data2,how='right') # right join

   key1  key2  key3  key4
0     1     3     2    76
1     2     2    81    43
2    44    46    54    78
3     6    87    22    98
4     8    67    56    60
5     3    76     9    66

In [68]:
pd.merge(data1,data2,how='outer',on='key2') # outer join,key2 common lo

   key1_x  key2  key3_x  key1_y  key3_y  key4
0     2.0     2     8.0     2.0    81.0  43.0
1     1.0     3     2.0     1.0     2.0  76.0
2     8.0     6    56.0     NaN     NaN   NaN
3     6.0     8   222.0     NaN     NaN   NaN
4     4.0    46    54.0    44.0    54.0  78.0
5     NaN    67     NaN     8.0    56.0  60.0
6     3.0    76     9.0     3.0     9.0  66.0
7     NaN    87     NaN     6.0    22.0  98.0

In [69]:
pd.merge(data1,data2,how='cross') # cross join(cartitian product

    key1_x  key2_x  key3_x  key1_y  key2_y  key3_y  key4
0        1       3       2       1       3       2    76
1        1       3       2       2       2      81    43
2        1       3       2      44      46      54    78
3        1       3       2       6      87      22    98
4        1       3       2       8      67      56    60
5        1       3       2       3      76       9    66
6        2       2       8       1       3       2    76
7        2       2       8       2       2      81    43
8        2       2       8      44      46      54    78
9        2       2       8       6      87      22    98
10       2       2       8       8      67      56    60
11       2       2       8       3      76       9    66
12       4      46      54       1       3       2    76
13       4      46      54       2       2      81    43
14       4      46      54      44      46      54    78
15       4      46      54       6      87      22    98
16       4      46      54       8      67      56    60
17       4      46      54       3      76       9    66
18       6       8     222       1       3       2    76
19       6       8     222       2       2      81    43
20       6       8     222      44      46      54    78
21       6       8     222       6      87      22    98
22       6       8     222       8      67      56    60
23       6       8     222       3      76       9    66
24       8       6      56       1       3       2    76
25       8       6      56       2       2      81    43
26       8       6      56      44      46      54    78
27       8       6      56       6      87      22    98
28       8       6      56       8      67      56    60
29       8       6      56       3      76       9    66
30       3      76       9       1       3       2    76
31       3      76       9       2       2      81    43
32       3      76       9      44      46      54    78
33       3      76       9       6      87      22    98
34       3      76       9       8      67      56    60
35       3      76       9       3      76       9    66

In [74]:
data1 = pd.DataFrame({'key1': [1, 2, 4, 6, 8, 3],
                      'key2': [3, 2, 46, 8, 6, 76],
                      'key3': [2, 8, 54, 222, 56, 9]
                      },
                     index = ['a','b','c','d','e','f']
                     )
data2 = pd.DataFrame({'key11': [1, 2, 44, 6, 8, 3],
                      'key22': [3, 2, 46, 87, 67, 76],
                      'key33': [2, 81, 54, 22, 56, 9],
                      'key4': [76, 43, 78, 98, 60, 66]
                      },
                     index = ['a','m','c','d','e','z']
                     )

In [75]:
data1

   key1  key2  key3
a     1     3     2
b     2     2     8
c     4    46    54
d     6     8   222
e     8     6    56
f     3    76     9

In [76]:
data2

   key11  key22  key33  key4
a      1      3      2    76
m      2      2     81    43
c     44     46     54    78
d      6     87     22    98
e      8     67     56    60
z      3     76      9    66

In [79]:
data1.join(data2) # join same as merge but operate on index, default left join

   key1  key2  key3  key11  key22  key33  key4
a     1     3     2    1.0    3.0    2.0  76.0
b     2     2     8    NaN    NaN    NaN   NaN
c     4    46    54   44.0   46.0   54.0  78.0
d     6     8   222    6.0   87.0   22.0  98.0
e     8     6    56    8.0   67.0   56.0  60.0
f     3    76     9    NaN    NaN    NaN   NaN

In [80]:
data1.join(data2,how='right')

   key1  key2   key3  key11  key22  key33  key4
a   1.0   3.0    2.0      1      3      2    76
m   NaN   NaN    NaN      2      2     81    43
c   4.0  46.0   54.0     44     46     54    78
d   6.0   8.0  222.0      6     87     22    98
e   8.0   6.0   56.0      8     67     56    60
z   NaN   NaN    NaN      3     76      9    66

In [81]:
data1.join(data2,how='inner')

   key1  key2  key3  key11  key22  key33  key4
a     1     3     2      1      3      2    76
c     4    46    54     44     46     54    78
d     6     8   222      6     87     22    98
e     8     6    56      8     67     56    60

In [82]:
df

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [83]:
# want to change fare euro to INR

In [84]:
df['Fare_INR'] = df['Fare'].apply(lambda x : x*80)

In [85]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,580.000
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,5702.664
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,634.000
3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S,644.000
4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q,676.664

In [86]:
df['Fare_INR']

0       580.000
1      5702.664
2       634.000
3       644.000
4       676.664
         ...
885    1040.000
886    2400.000
887    1876.000
888    2400.000
889     620.000
Name: Fare_INR, Length: 890, dtype: float64

In [87]:
# want to store length of name

In [88]:
df['Name_Len']= df['Name'].apply(len)

In [89]:
df

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR,Name_Len
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,580.000,23
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,5702.664,51
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,634.000,22
3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S,644.000,24
4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q,676.664,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S,1040.000,21
886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S,2400.000,28
887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1876.000,40
888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C,2400.000,21
889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q,620.000,19